title: cxzaqwed
url: https://cxzaqwed.github.io
author: cxzaqwed
email: cxzaqwed@protonmail.ch
description: > # this means to ignore newlines until "show_exerpts:"
  I like to know how everything works on this simulation called "life". I test, explore, create, and everything else that Science help us to do.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"


  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/cxzaqwed22
      icon: twitter-square
      color: cyan
    - url: https://www.twitch.tv/cxzaqwed22
      icon: twitch
      color: purple
    - url: https://github.com/cxzaqwed
      icon: github-square
      color: yellow
    - url: https://steamcommunity.com/id/cxzaqwed/
      icon: steam
      color: yellow
    - url: https://www.linkedin.com/in/cxzaqwed/
      icon: linkedin
      color: yellow

# Build settings
theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging
